app/components/codelist-form.hbs, app/components/codelist-form.js, app/models/skos-concept.js, package-lock.json, package.json, tests/unit/models/code-list-test.js
This PR includes an update to ember-data 3.28.12. Ember-data 3.28 includes some changes to relationships which broke some of the functionality of the app. This PR thus additionally includes changes to the models and components.
- Update to ember data 3.28.12
- Add polymorphic attribute to necessary models
- Move constructor contents to didInsert hooks so relationships can be properly awaited.
=> Update ember-data to 3.28

package-lock.json, package.json
Update generate-template-plugin which fixes issues when exporting the html from the document. This prevents issues with the table of contents being incorrectly exported.
Solves https://binnenland.atlassian.net/browse/GN-3682?atlOrigin=eyJpIjoiMjQzMDI0OTU1Yzk3NDk0ZmI3Yzc4YzJjY2UxNTdhOGIiLCJwIjoiaiJ9.
=> Bump generate-template-plugin

package-lock.json, package.json
This PR includes an update of the generate template to 0.1.5. 0.1.5 fixes an issue with incorrectly formatted `generateUuid()` placeholders.
=> Bump generate template plugin to 0.1.5

app/controllers/list.js, app/controllers/publish.js, app/models/regulatory-attachment-publication-task.js, app/routes/list.js, app/routes/publish.js, app/services/mu-task.js
This PR includes some changes which refresh the data of the route when having removed or published a regulatory statement template.
TODO:
=> Refresh data when a regulatory statement has been removed or published

app/controllers/publish.js, app/templates/publish.hbs, translations/en-us.yaml, translations/nl-BE.yaml
This PR includes two new features:
- The addition of a navigation bar on the publish page which allows a user to go back to the edit page.
- A notification is shown when the template has been successfully published.
This PR solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3768.
=> Navigation of publish page and addition of `published` notification

app/components/app-chrome.hbs, app/components/app-chrome.js, app/components/editor-document-title.hbs, app/components/editor-document-title.js
This ensures that the title of the document is saved just after having edited it. An additional save of the document is no longer required. Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3734.
=> Save document title after editing it

app/components/codelist-form.hbs, app/controllers/codelists-management/index.js, app/controllers/edit.js, app/controllers/list.js, app/controllers/publish.js, app/models/code-list.js, app/models/document-container.js, app/models/editor-document.js, app/models/published-regulatory-attachment-container.js, app/models/published-regulatory-attachment.js, app/models/regulatory-attachment-publication-task.js, app/models/regulatory-statement.js, app/router.js, app/routes/codelists-management/new.js, app/routes/edit.js, app/routes/list.js, app/routes/publish.js, app/templates/codelists-management/index.hbs, app/templates/list.hbs, app/templates/publish.hbs, config/environment.js, translations/en-us.yaml, translations/nl-BE.yaml
I added to the list page of regulatory statements, following functionalities:
- sort on modified date by default
- include the modified and published dates
- allow filtering on title
- support pagination
Please let me know If I'm missing something? Thanks
=> GN-3766 - The overview page of frontend-rb should be sorted by default

app/components/app-chrome.hbs, app/components/app-chrome.js, app/helpers/human-friendly-date.js
This PR ensures that we can show human-readable dates in the current locale of the user.
Solves https://binnenland.atlassian.net/browse/GN-3944?atlOrigin=eyJpIjoiMDY0ODBlNjUzMzkzNDkyNWEwZDAwNWRjMTQ4YzE5MGIiLCJwIjoiaiJ9.
=> Update human-friendly date to accept a specific locale

app/controllers/edit.js
To be honest I don't know why this is needed. But it fixes the issue
In GN it doesn't happen because the editor is not rendered on a top route, maybe we should reestructure the routes of this app.
Solves https://binnenland.atlassian.net/browse/GN-4332
=> fixed currrentSession.group can be undefined

app/controllers/list.js
this tripped an assertion that only runs in dev mode, not in prod 
it is not allowed to set relationships with a direct string ID, you need to fetch the model instance first
in any case, the line was redundant, since we later remove the instance entirely
=> fix(overview): remove erroneous setting of a relationship with a string

app/templates/codelists-management/index.hbs
This PR fixes a translation issue with the type attribute of a codelist on the codelist overview page.
Related Jira ticket: https://binnenland.atlassian.net/browse/GN-4377
=> Fix type translation on codelist overview page

package-lock.json, package.json
This PR updates `@lblod/ember-rdfa-editor` to version 3.10
=> Update `@lblod/ember-rdfa-editor` to 3.10

package-lock.json, package.json
Updates `@lblod/ember-rdfa-editor-lblod-plugins` package to 8.1.0
=> Update `@lblod/ember-rdfa-editor-lblod-plugins` to 8.1.0

app/components/codelist-form.hbs, app/components/confirm-route-leave.hbs, app/components/confirm-route-leave.js, app/templates/edit.hbs, app/templates/snippets-management/edit/edit-snippet.hbs, translations/en-us.yaml, translations/nl-BE.yaml
- Restructures the modal-route-leave so it shows an actual modal instead of a `window.confirm` box (which is more ugly and less accessible).
- also adds this logic for codelist form, where it was missing
https://binnenland.atlassian.net/browse/GN-4364
! The code is mainly based on work done in https://github.com/lblod/frontend-reglementaire-bijlage/pull/88/files#diff-4d405f6a17a3bc1e4537a824815deb278077401573a7af5229d973c0ffa3a7a1
go to the creation/editing of a regulatory statement, snippet (document, not snippet list) or codelist.
Make any change and try to navigate away via buttons or browser navigation. Make sure the modal shows up, the buttons work as expected and the history stays intact.
Note that refreshing or closing the tab can't be stopped and does not make the modal show up. …
=> Use AuModal for the modal shown when leaving a route

app/components/app-chrome.js, app/controllers/snippets-management/edit/edit-snippet.js, app/templates/snippets-management/edit/edit-snippet.hbs
Updates published snippet when snippet name updated
https://binnenland.atlassian.net/browse/GN-4443
1. Get https://github.com/lblod/app-reglementaire-bijlage
2. Run `app-reglementaire-bijlage`
3. Checkout this branch
6. Inside `frontend-reglementaire-bijlage` do `npm i` and server it with `ember s --proxy http://localhost`
Modified `frontend-reglementaire-bijlage` should be running on localhost on port 4200.
* Go to http://localhost:4200/mock-login to login into RB frontend
* Create a Snippet List, and create a snippet within that list. Observe that all is working, snippet is saved and there are no console/network errors.
* Go to Regulatory Attachments and try to insert the snippet
* Go back to Snippet and rename it
* Go to Regulatory Attachments and see that Snippet name got changed …
=> GN-4443: Update published snippet on snippet name change

app/controllers/regulatory-attachments/edit.js, app/templates/regulatory-attachments/edit.hbs
This PR adds the new template comments feature to the regulatory-statement edit page. It allows users to insert a comment/example in a template. This comment is to be removed upon publishing a regulatory statement.
=> Enable template comments on regulatory statement edit page

.changeset/fair-ties-rule.md, app/controllers/regulatory-attachments/edit.js, app/controllers/snippets-management/edit/edit-snippet.js, translations/en-us.yaml, translations/nl-BE.yaml
The entries in the insert-variable dropdown component were still hardcoded in english, this PR ensures that these are properly internationalized.
- Open a regulatory statement template/snippet
- Check if the variable-insert dropdown is properly internationalized
=> Add translations to variable-insert dropdown

translations/en-us.yaml, translations/nl-BE.yaml
This PR corrects the production website URL in the footer of this application to register.reglementairebijlagen.vlaanderen.be (hotfix to version 6.7.0)
=> Fix website url in footer (hotfix)

.changeset/fair-geese-buy.md, app/components/editor-document-title.hbs, app/components/editor-document-title.js, app/components/snippet-list-form.hbs, app/components/snippet-list-form.js, app/controllers/regulatory-attachments/index.js, app/templates/regulatory-attachments/index.hbs
The initial problem to fix was to save the title also when saving the document.
Fixing this is not trivial in a sense: saving the title is deep in a child (EditorDocumentTitle) while saving the document is with an action passed to the main component.
However, as mentioned in the ticket, it is also desired to save when losing focus of the input (`onblur`). This automatically fixes the issue: if a user presses the document-save button, it will unblur the title input and automatically also save that.
This is the first commit.
All other commits are cleanup of code which this auto-save feature put into attention.
- Empty titles are not permitted (this was already not meant to be possible and was mentioned in a previous PR, but seems it got through anyway).
- Auto-saving didn't let the error …
=> Also save title when saving document + fix save pill and don't allow empty titles

.changeset/fluffy-jeans-share.md, app/utils/generate-template.js
All instances of one uri are replaced with the same call to `generateBoundUuid()`, so they will receive the same uri in the new document.
BREAKING: requires GN to support `generateBoundUuid()` (>5.7.0)
https://binnenland.atlassian.net/browse/GN-4505
Requires: https://github.com/lblod/frontend-gelinkt-notuleren/pull/586
Related: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/315
To test import into GN, need to set `regulatoryStatementEndpoint` and `regulatoryStatementFileEndpoint` in config/environment.js in that project to point to your local RS.
Backwards compat can be tested by creating a template regulatory attachment and then instantiating it in [GN](https://github.com/lblod/frontend-gelinkt-notuleren/pull/586).
Maintaining relationships can be tested by duplicating …
=> GN-4505 Generate attachment templates which maintain relationships between nodes

.changeset/polite-cars-lie.md, app/components/footer.hbs, app/components/static-page.hbs, app/templates/legal.hbs, app/templates/legal/accessibilitystatement.hbs, app/templates/legal/cookiestatement.hbs, app/templates/legal/disclaimer.hbs
This PR ensures that the legal pages of this application (the accessibility statement, cookiestatement and disclaimer) are filled out.
[GN-4563](https://binnenland.atlassian.net/browse/GN-4536?atlOrigin=eyJpIjoiZDZmNTVlOGRjYTIxNGQzNWE1YWQyMjQwZDA2NjcwZTkiLCJwIjoiaiJ9)
- start the application
- check out the legal pages (linked in the footer)
- ensure that the text on the legal pages is displayed correctly
- I took over the content of the legal pages from the [GN](https://github.com/lblod/frontend-gelinkt-notuleren) application including some modifications.
=> GN-4536: fill out legal pages

.changeset/small-seals-talk.md, app/controllers/regulatory-attachments/edit.js
GN-4628: Change attribute name used to store snippet list IDs
`snippet-list-ids` was not a valid attribute name. Changed to `data-snippet-list-ids`.
https://binnenland.atlassian.net/browse/GN-4628
1. Checkout
Open up http://localhost:4200/mock-login and try to perform the same activities as in linked video.
https://share.cleanshot.com/v3YsRvbh
=> GN-4628: Change attribute name used to store snippet list IDs

.changeset/lovely-queens-kiss.md, app/templates/regulatory-attachments/edit.hbs, app/templates/snippets-management/edit/edit-snippet.hbs, translations/en-us.yaml, translations/nl-BE.yaml
In the sidebar, this used to say 'Insert':
https://binnenland.atlassian.net/browse/GN-4665
Recommended, some way to change locales easily, e.g. [this extension](https://addons.mozilla.org/en-US/firefox/addon/locale-switcher/)
Open any regulatory attachment and confirm that the word 'insert' is in the correct language (NL for anything but locale of en-US).
I don't know the correct dutch and there seems to be difference with the `insert-label` translation.
=> Add translation for 'insert' in the sidebar

.changeset/rich-deers-double.md, app/controllers/regulatory-attachments/edit.js, app/controllers/snippets-management/edit/edit-snippet.js, app/templates/regulatory-attachments/edit.hbs
Use the new logic from [GN](https://github.com/lblod/frontend-gelinkt-notuleren/pull/614) of using the undo state to determine if there are unsaved changes.
I also fixed the display of 'there are unsaved changes' for attachments as this was not wired in.
[PR on GN](https://github.com/lblod/frontend-gelinkt-notuleren/pull/614)
https://binnenland.atlassian.net/browse/GN-4016
N/A
Open a regulatory attachment or snippet, make an edit (or not), then attempt to leave.
N/A
=> Copy logic of using undo state to determine if there are unsaved changes

.changeset/quick-news-shave.md, app/templates/regulatory-attachments/publish.hbs
This PR adds the `say-content` class to the template previews in order to include editor styling.
Solves [GN-4654](https://binnenland.atlassian.net/browse/GN-4654?atlOrigin=eyJpIjoiZjNhN2E1OTRiZDY5NDU4OTk2NTYyMzI3YTFhZDU4ZWEiLCJwIjoiaiJ9) partly
- Open a template
- Insert an ordered list
- On the preview page, notice that the list numbers show up
=> GN-4654: add editor styling to template previews

.changeset/soft-baboons-fry.md, app/templates/regulatory-attachments/edit.hbs
This PR adds a null-check to the `activeNode` property before passing it to the `SnippetInsert` component, to ensure that we're not passing an undefined node to the component.
[GN-4733](https://binnenland.atlassian.net/browse/GN-4733?atlOrigin=eyJpIjoiYTZlYWU0Y2ZiOThiNDBkZDgxMWYyNjc5NmQzNmFjMzkiLCJwIjoiaiJ9)
- Start the application
- Open a regulatory statement in which snippet lists are active/allowed
- Click on a (citation) link
- Notice that no `node` is undefined error shows up
=> GN-4733: fix node is `undefined` error

.changeset/cuddly-poems-kneel.md, app/controllers/application.js, app/templates/application.hbs
This PR ensures that the breadcrumbs toolbar is not shown in the following cases:
- When on the index page
- When not authenticated
None
- Start up the frontend
- On the index/login page, the breadcrumbs toolbar should not be visible
- Once logged in, the toolbar should be visible on any other page
=> Ensure breadcrumbs toolbar is only shown when applicable

.changeset/loud-cows-fetch.md, app/controllers/regulatory-attachments/publish.js, app/controllers/snippets-management/edit/edit-snippet.js, app/models/regulatory-attachment-publication-task.js, app/models/snippet-list-publication-task.js, app/templates/snippets-management/edit/edit-snippet.hbs
This PR removes the `snippet-list-publication-task` and `regulatory-attachment-publication-task` models and replaces them by simple fetch requests. 
This is done for two reasons:
- Ember Data is not really leveraged for these tasks, they only are posted using ember-data, not fetched.
- The content/structure of a task is not really consistent. The request body is not equal to the format of the response body of a task, so it does not following JSON:API correctly.
The functionality of this app should remain the same. The requests made to the backend remain the same
I understand moving away from ED for these tasks is an opinionated change, maybe it is deemed better to keep using ED for the tasks. In that case we should ensure that the backend (the reglement-publish-service) follows the …
=> Drop ember-data `task` models

.changeset/five-students-collect.md, app/services/mu-task.js
Visit https://github.com/lblod/app-reglementaire-bijlage/pull/78 for a summary of the changes included in this PR.
=> Use `/tasks/:id` endpoint to fetch information/status of a task.

.changeset/sweet-bees-enjoy.md, .changeset/swift-falcons-pump.md, app/controllers/regulatory-attachments/edit.js, app/controllers/snippets-management/edit/edit-snippet.js, app/templates/regulatory-attachments/edit.hbs, app/templates/snippets-management/edit/edit-snippet.hbs, package-lock.json, package.json
This PR includes two changes:
- Update of `@lblod/ember-rdfa-editor` to 9.7.0
- Support for hierarchical lists
=> Update `@lblod/ember-rdfa-editor` to 9.7.0 and enable support for hierarchical lists

.changeset/lucky-ways-glow.md, app/components/confirm-route-leave.js, app/controllers/regulatory-attachments/edit.js
So basically the problem is that when you save for the first time a race condition makes that the editor is flagged as dirty. So the confirm modal cancels the transition.
My proposed solution is to add these queryParams in order to override the confirm modal when we know the document has just been saved. May not be the best solution so please comment on it if you have a better one
GN-4687
This only happens on production build, so you will need to build a docker image for it
create a new regulatory statement, modify it, and then click on save and publish
=> Made possible to override the confirm modal

.changeset/metal-badgers-judge.md, app/controllers/regulatory-attachments/publish.js, app/routes/regulatory-attachments/index.js, app/services/mu-task.js
Included published version on RB query because it was caching it in the production mode, resulting in wrong information being shown
GN-4575
You will need to use a built version of the frontend in order to reproduce, because it worked perfeclty fine on dev
Go to RB, create a new one, publish it and go back to the index, the published date should be correct
None
=> Fix publication date of RB not being updated

.changeset/purple-ducks-buy.md, .woodpecker/.release.yml
The release woodpecker build is only pushing to the specific version tag, not to `:latest`, so `:latest` is actually pushed from the latest script. Woodpecker doesn't seem to run latest for the release commit, presumably either because it triggers the release pipeline, or because it's pushed at the same time, so there's only one 'push' event (not sure why it wouldn't pick the latest pushed commit though).
So until the first change to master after a release, `:latest` will always misreport as being the previous version.
N/A
N/A
Push a new tag and verify in docker hub that the shas for both that version and `latest` are the same.
I don't know for sure if this will work, their docs don't say how to specify multiple tags, but their code looks like just comma seperating works.
=> Correctly tag release builds as latest in docker hub

.changeset/unlucky-seals-collect.md, app/controllers/snippet-management/index.js, app/routes/snippet-management/index.js, app/templates/codelist-management/index.hbs, app/templates/snippet-management/index.hbs, app/templates/template-management/index.hbs, translations/en-us.yaml, translations/nl-BE.yaml
Added a search field on the snippet list page
GN-4936
None
Go to the snippet list page and you should be able to search by label
None
=> Add search to the snippet management page

.changeset/three-vans-tie.md, app/templates/codelist-management/index.hbs, app/templates/snippet-management/index.hbs, app/templates/template-management/index.hbs
This PR adds a `no-case` modifier to sortable string fields (relevant in the snippet, template and codelist overviews). This ensures that sorting on title/label alphabetically works as expected.
[GN-4957](https://binnenland.atlassian.net/browse/GN-4957)
- Start the app
- Open up one of the overview pages (snippets/templates/codelists)
- Ensure sorting on title/label works as expected
The `no-case` modifier is required for both case-insensitive sorting and for string sorting to work. (string sorting does not work in combination with `MAX` in sparql queries due to a bug in virtuoso).
=> GN-4957: add `no-case` modifier where necessary

.changeset/nice-avocados-study.md, ember-cli-build.js
This PR excludes ember-leaflet assets from fingerprinting
[GN-4976](https://binnenland.atlassian.net/browse/GN-4976?atlOrigin=eyJpIjoiMTM5ZjEzZmUzZWFmNDZjYWI3ZTJmZWI5OWI1MmJhN2YiLCJwIjoiaiJ9)
Check-out https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/464 for more information.
=> GN-4976: disable fingerprinting on ember-leaflet assets

.changeset/green-roses-pretend.md, .changeset/slimy-mangos-drive.md, app/controllers/snippet-management/edit/edit-snippet.js, app/templates/snippet-management/edit/edit-snippet.hbs, app/templates/template-management/edit.hbs, package-lock.json, package.json, translations/en-us.yaml, translations/nl-BE.yaml
This (draft) PR adds two different features/adjustments:
- Support for inserting decision articles in snippets
- A restructure of the snippet editor sidebar which now contains 3 seperate insert sections:
* Algemene nodes (General nodes): contains actions such as inserting dates, citations etc.
* Besluit nodes (Decision nodes): contains actions such as inserting a mandatee table, decision article
* Reglementaire Bijlage nodes (Regulatory statement nodes): contains actions such as inserting article structures, document titles
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/471
- Start the application
- Open a snippet in the editor
- Notice that the sidebar is now divided into 3 insert sections
- You should be able to insert decision articles anywhere in the snippet
Unsure …
=> Support decision articles in snippets

.changeset/lovely-buckets-press.md, app/templates/snippet-management/edit/edit-snippet.hbs, app/templates/template-management/edit.hbs
The user of RB is not from any municipality, so there's no meaningful list of people that they could insert. Further, if they could insert any 'person', then this would make templates that are specific to the relevant municipality for that person, which does not make sense.
Although https://github.com/lblod/app-reglementaire-bijlage/pull/82 makes vendor-proxy work, there are still no people to insert.
Part of Jira ticket https://binnenland.atlassian.net/browse/GN-5018
N/A
You can insert person placeholders using the variable drop-down, but not insert the actual person.
N/A
=> Remove person variable edit components as templates can't contain people

.changeset/strong-tomatoes-bake.md, app/components/search-form.hbs, app/controllers/codelist-management/index.js, app/controllers/snippet-management/index.js, app/controllers/template-management/index.js, app/styles/app.scss, app/templates/codelist-management/index.hbs, app/templates/snippet-management/index.hbs, app/templates/template-management/index.hbs, translations/en-us.yaml, translations/nl-BE.yaml
This PR includes a rework of the search-form/search-bar which is used on the 3 main overview pages:
- snippet-management
- codelist-management
- template-management
Specifically, the rework includes:
- A new reusable `search-form` component, with an explicit button
- No automatic searches. Search is only performed when clicking the search-icon/button, or pressing enter
- Removal of debounced search, as it is no longer needed.
Fixes [GN-4956](https://binnenland.atlassian.net/browse/GN-4956?atlOrigin=eyJpIjoiYTRhZjExMzExMTNhNDE2NmEyNjE4M2QwMjYyMzY4OWUiLCJwIjoiaiJ9)
None
- Start the application
- Visit any of the overview screens
- Ensure you can search the items using the new search form
- The search form should also be navigable with `tab`.
- You should be able to use `Enter` to search
- …
=> GN-4956: search bar rework

.changeset/violet-tips-fly.md, app/components/snippet-list-form.hbs, app/templates/snippet-management.hbs, app/templates/snippet-management/edit.hbs, app/templates/snippet-management/edit/edit-snippet.hbs, app/templates/snippet-management/edit/index.hbs, app/templates/snippet-management/index.hbs, app/templates/snippet-management/new.hbs, translations/en-us.yaml, translations/nl-BE.yaml
This PR includes two changes:
- A restructure of the snippet translations to better reflect the different routes/components
- Some corrections to the dutch translations + some new translations
None
- Open the app
- Visit the pages related to snippets
- The dutch translations should be improved/more correct
- Some translations (like the 'no-data' translations) should be more correct
I restructured the translations in a way that made more sense to me/is easier extendable, feel free to comment if you think the restructure is less clear/too verbose :)
=> i18n: restructure snippet translations

.changeset/flat-drinks-know.md, app/controllers/snippet-management/edit/edit-snippet.js
This PR disables the `rdfaAware` setting for `heading` nodes in the snippet editor.
The `rdfaAware` setting never really worked very well in combination with `heading` nodes. Typically (IMO) it's not a good idea to mix markup/styled nodes (e.g. headings, paragraphs) with data nodes (block_rdfa, inline_rdfa...)
None
None
- Start the frontend
- Open a snippet
- Insert any heading
- It should be non-rdfa aware, you should also be able to easily enter inside of it.
- In the future, we should probably parse heading nodes containing RDFa as `block_rdfa` nodes with a `heading` node inside. I'll make a Jira ticket to track this.
=> Disable `rdfaAware` setting for `heading` nodes in snippet editor

.changeset/spotty-plants-jump.md, app/components/rdfa-editor-container.js
This PR adds the `emberApplication` prosemirror plugin to the list of configured plugins for the snippet and template editors.
This ensures that the serialization methods of the configure prosemirror node-specs have access to the ember application, which allows them to leverage `ember-intl` to provide internationalized serializations.
This thus also fixes the non-internationalized article serialization bug.
[GN-5150](https://binnenland.atlassian.net/browse/GN-5150)
None
- Start the app
- Open a template
- Add a decision article to the template
- Save the template and go to the publish screen
- Notice that the serialized article is now correctly internationalized (following the document language)
=> GN-5150: configure `emberApplication` prosemirror plugin

.changeset/quick-falcons-flow.md, app/components/snippet-list-form.hbs, app/components/snippet-list-form.js, app/controllers/snippet-management/edit/edit-snippet.js, app/controllers/template-management/edit.js, app/models/document-container.js, app/models/snippet-list.js, app/models/snippet.js, app/routes/snippet-management/edit.js, app/services/store.js, app/utils/extract-snippet-lists.js, package-lock.json, package.json, translations/en-us.yaml, translations/nl-BE.yaml
This PR fixes and extends the functionality of displaying the connected documents (templates and snippets) when editing a snippet-list:
- `SnippetList` model: remove unnecessary `templates` relationship
- `DocumentContainer` model: rename `snippetLists` relationship to `linkedSnippetLists`
- `Snippet` model: add `linkedSnippetLists` relationship
- Extend `snippet-list` edit page to include both connected templates *and* connected snippets
- Add `@lblod/marawa` dependency to allow for RDFa document parsing
- Ensure the connected snippet-lists are extracted and stored on saving templates/snippets
[GN-5055](https://binnenland.atlassian.net/browse/GN-5055)
Requires https://github.com/lblod/app-reglementaire-bijlage/pull/85
Ensure you're running the RB stack locally, with the following PR …
=> GN-5055: connected-snippet-lists - fix and extend functionality

.changeset/purple-cameras-change.md, app/controllers/template-management/edit.js, app/routes/template-management/edit.js
This PR includes two adjustments/fixes:
- `TemplateManagementEditRoute`: drop the `snippet-lists` relationship from the include in the `document-container` query
- `TemplateManagementEditController`: remove obsolete/unused method
https://github.com/lblod/frontend-reglementaire-bijlage/pull/299
None
- Start the frontend
- Open a template
- No HTTP error should occur, the template should open as usual
=> Fix http error when opening templates

.changeset/silly-nails-yawn.md, package-lock.json, package.json
Update `@lblod/ember-rdfa-editor` to version [10.9.0](https://github.com/lblod/ember-rdfa-editor/releases/tag/v10.9.0)
=> Update editor to version 10.9.0

.changeset/shy-ravens-turn.md, app/components/app-chrome.hbs, app/components/app-chrome.js, app/components/confirm-modal.hbs, app/components/confirm-modal.js, app/components/confirm-route-leave.hbs, app/controllers/template-management/edit.js, app/controllers/template-management/index.js, app/controllers/template-management/publish.js, app/routes/template-management/edit.js, app/templates/template-management/edit.hbs, app/templates/template-management/index.hbs, app/templates/template-management/publish.hbs, translations/en-us.yaml, translations/nl-BE.yaml
Add controls for unpublishing templates and update UI to display details of published status.
PR to fix resources config for `validThrough`: https://github.com/lblod/app-reglementaire-bijlage/pull/86
Jira ticket: https://binnenland.atlassian.net/browse/GN-5192
Needs to be pointing to an RB backend with the resources fix. To test, use GN, pointing to this RB.
You should be able to publish and unpublish templates however you like. Only when published they will be visible in the new agendapoint or regulatory statement modals.
You should also be able to test setting an expiry date by setting the 'validThrough' for a template to be in the future.
The UI was unknown, so I just based my work on what was already there...
=> Functionality for unpublishing templates

.changeset/healthy-boxes-jog.md, app/controllers/snippet-management/edit/edit-snippet.js, app/controllers/template-management/edit.js, package-lock.json, package.json
Just a matter of adding the new configuration.
A draft until plugins PR is merged.
Plugins PR: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/517
GN PR: https://github.com/lblod/frontend-gelinkt-notuleren/pull/794
Jira ticket: https://binnenland.atlassian.net/browse/GN-5022
N/A
Same as plugins PR, for templates or snippets. Should handle the type of template correctly.
I wasn't sure if we should do this on RSs, but I made a guess.
=> Link locations to the surrounding document on insertion

.changeset/sharp-starfishes-yawn.md, app/models/task.js, app/services/mu-task.js, app/utils/constants.js
This PR includes two internal changes:
- Usage of more generic task 'status' URIs
- Use ember-data + mu-cl-resources to fetch tasks using JSON:API
https://github.com/lblod/reglement-publish-service/pull/19
https://github.com/lblod/app-reglementaire-bijlage/pull/88
Check-out https://github.com/lblod/app-reglementaire-bijlage/pull/88 for instructions
Check-out https://github.com/lblod/app-reglementaire-bijlage/pull/88 for instructions
=> Slightly rework mu-task handling

.changeset/fluffy-queens-double.md, app/components/snippet-list-form.js, app/controllers/template-management/edit.js, app/controllers/template-management/index.js
When saving a template (`editor-document`), correctly link it to its respective `document-container`.
**Update: this also fixes the following issues**
- When creating a new snippet, correctly link the snippet to snippet-version
- Fix an issue with the `undefined` in the url created when creating a snippet
https://github.com/lblod/app-reglementaire-bijlage/pull/90
Check-out https://github.com/lblod/app-reglementaire-bijlage/pull/90 for more information
=> Correctly link `document-container` resources to their `editor-document` versions

.changeset/neat-spiders-hide.md, app/components/file-upload-button.gjs, app/components/snippet-list-form.hbs, app/components/template-exporter.gjs, app/components/template-importer.gjs, app/services/current-session.js, app/templates/codelist-management/index.hbs, app/templates/snippet-management/index.hbs, app/templates/template-management/publish.hbs, app/utils/changeset.js, tests/unit/models/code-list-test.js
This PR includes a removal of (most) deprecations introduced in ember 5.x.
It's possibly best to test with the `EXTEND_PROTOTYPES` flag set to false, just be aware that ember-drag-drop won't work, so that will need to be tested with it not set.
- Ensure every page/function works as before
- Pay special attention to the codelist edit page, as I had to make some internal changes to the `ChangesetList` implementation
=> Cleanup deprecations introduce in Ember 5.x

.changeset/dry-tips-teach.md, .woodpecker/.verify-pr.yml, Dockerfile, README.md, package.json, patches/ember-source@5.12.0.patch, pnpm-lock.yaml
This PR moves this application from npm to pnpm.
Additionally, it also includes the following changes:
- a `packageManager` field in the `package.json` file, to be easily used in conjunction with corepack
- Some required modifications to the pnpm overrides
- Drop `patch-package` in favor to the native `pnpm.patchedDependencies` setting
- Ensure `pnpm install` works well :)
=> Move to pnpm

app/components/rdfa-editor-container.hbs, app/styles/_shame.scss, app/styles/app.scss, app/templates/snippet-management/edit/edit-snippet.hbs, app/templates/template-management/edit.hbs, app/templates/template-management/publish.hbs
This PR includes adjustments to support the removal of the legacy RDFa annotation feature.
It builds upon https://github.com/lblod/ember-rdfa-editor/pull/1241 and https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/529
Specifically, this PR includes the following:
- Removed the rdfa-annotations toggle
- Removed imports of certain legacy stylesheets
- Removed usage of legacy `rdfa-annotation` classes
[GN-5171](https://binnenland.atlassian.net/browse/GN-5171?atlOrigin=eyJpIjoiNjI1NWY4M2Q5YTM3NDIwZWFlNTQxYjUzN2M0ZTgxNmEiLCJwIjoiaiJ9)
https://github.com/lblod/ember-rdfa-editor/pull/1241
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/529
- Start the app
- Open the different type of editors used throughout the application + ensure their styling is still correct
- …
=> GN-5171: drop legacy rdfa annotation feature

.changeset/fair-numbers-film.md, .changeset/few-rings-dream.md, app/controllers/template-management/edit.js, package.json, pnpm-lock.yaml
This PR updates the following packages:
- `@lblod/ember-rdfa-editor` to version [11.2.0](https://github.com/lblod/ember-rdfa-editor/releases/tag/v11.2.0)
- `@lblod/ember-rdfa-editor-lblod-plugins` to version [28.0.0](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/releases/tag/v28.0.0)
This PR also includes an adjustment to support the new table-of-contents API.
=> Update editor packages

.changeset/khaki-teachers-tan.md, package.json, pnpm-lock.yaml
Just an update to the latest plugins.
Jira ticket: [binnenland.atlassian.net/browse/GN-5525](https://binnenland.atlassian.net/browse/GN-5525)
Plugins PR: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/559
GN PR: https://github.com/lblod/frontend-gelinkt-notuleren/pull/841
Can be useful to test alongside the GN PR as the published templates and snippets should have the correct styling when published using this version.
Publish previews show any variables (or OSLO locations) highlighted in orange. These should also show up correctly in GN (with the correct branch).
N/A
=> Style variables as orange in previews

.changeset/pretty-radios-refuse.md, app/styles/app.scss
Remove usage of default power-select styles, these conflict with the styles provided by appuniversum
- Start the app and open a page contain a power-select component
- Ensure that the power-select is now displayed correctly and no longer contains any visual bugs
=> fix(styling): remove conflicting powerselect styles
