lblod/frontend-reglementaire-bijlage

app/components/app-chrome.hbs, app/components/editor-document-title.hbs, app/styles/app.scss, app/templates/application.hbs, app/templates/codelists-management/index.hbs, app/templates/list.hbs
- fix scroll behaviour
- implement toc tweaks
- add breadcrumbs
- cleanup app chrome design
=> Minor design improvements

app/components/codelist-form.hbs, app/components/codelist-form.js, translations/en-us.yaml, translations/nl-be.yml
This should improve a little bit the codelist management page
=> solved bugs with adding empty codelist and added translations

app/components/codelist-form.hbs, app/components/codelist-form.js, app/components/codelist-option-form.hbs, app/components/codelist-option-form.js, app/templates/codelists-management/codelist.hbs, app/validations/codelist-option.js, translations/en-us.yaml, translations/nl-be.yml
This PR adds detailed validation when creating or editing codelist options. Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3671.
=> Add more validations to codelist creation and edit workflow

app/components/app-chrome.hbs, app/controllers/edit.js, app/templates/edit.hbs
https://binnenland.atlassian.net/browse/GN-3683
=> Save before going to publish

app/controllers/list.js, app/controllers/publish.js, app/routes/edit.js, app/routes/publish.js, app/templates/publish.hbs
Improved publication UX according to this Jira ticket https://binnenland.atlassian.net/browse/GN-3679
=> Improvements on publication UX according to Jira

app/components/codelist-option-form.hbs, package-lock.json, package.json
Solves https://binnenland.atlassian.net/browse/GN-3684?atlOrigin=eyJpIjoiYTA3ZThjMTQ5N2M1NDVjMTk4MjFiOGZkMTQxZmRmOTgiLCJwIjoiaiJ9.
Dependent on https://github.com/appuniversum/ember-appuniversum/pull/326.
=> Convert codelist creator to form and automatically focus the first input

app/templates/sparql.hbs
This PR provides the option to scroll the sparql page in order to ensure all its contents are visible. Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3731.
=> Bugfix: ensure sparql page is scrollable

app/templates/application.hbs, translations/en-us.yaml, translations/nl-BE.yaml
Solves https://binnenland.atlassian.net/browse/GN-3833?atlOrigin=eyJpIjoiOTAzNDJmMTlmNWUwNGIyNmJjYWI1M2RlODc4NzQxYWEiLCJwIjoiaiJ9
=> Remove switch organization functionality

app/components/confirm-route-leave.js, app/controllers/edit.js, app/routes/edit.js, app/templates/edit.hbs, app/utils/is-loading-route.js, translations/en-us.yaml, translations/nl-BE.yaml
Add a prompt when a user tries to leave a page with a document that has changes without saving
=>   Add a prompt when a user tries to leave a page with a document that has changes without saving

app/components/rdfa-editor-container.hbs, app/components/rdfa-editor-container.js, app/controllers/edit.js, app/styles/_shame.scss, app/templates/edit.hbs, package-lock.json, package.json, translations/en-us.yaml, translations/nl-BE.yaml
Solves https://binnenland.atlassian.net/browse/GN-3909
=> Add saving animation to reglement edit

translations/nl-BE.yaml
Solves https://binnenland.atlassian.net/browse/GN-3945?atlOrigin=eyJpIjoiZDlhNWM1ZjMzNzBhNGVkMDlkZjc5MzYyNGRjYzEwZjkiLCJwIjoiaiJ9.
=> Add dutch translation for `orderLabel`

app/templates/application.hbs
Partial solution for https://binnenland.atlassian.net/browse/GN-3944?atlOrigin=eyJpIjoiNmU3ZGU2MDZjNTllNDAzNWEzNjM5YjYwYzU1YzE1MTciLCJwIjoiaiJ9
=> Use translated app name in header

app/components/app-chrome.hbs, app/components/codelist-form.hbs, app/components/codelist-option-form.hbs, app/components/editor-document-title.hbs, app/components/static-page.hbs, app/controllers/publish.js, app/templates/application.hbs, app/templates/codelists-management/codelist.hbs, app/templates/codelists-management/edit.hbs, app/templates/codelists-management/index.hbs, app/templates/codelists-management/new.hbs, app/templates/edit.hbs, app/templates/index.hbs, app/templates/list.hbs, app/templates/mock-login.hbs, app/templates/publish.hbs, translations/en-us.yaml, translations/nl-BE.yaml
Currently we use a mix of dash-case and camelCase for translations in our projects. This PR aims to make this more consistent.
=> Remove unused translations and convert translations to kebab-case to ensure consistency

app/templates/edit.hbs
This PR is related with: https://github.com/lblod/ember-rdfa-editor/pull/733
=> "insert" card should be collapsible but open by default

app/controllers/edit.js, app/templates/edit.hbs, package-lock.json, package.json
@lagartoverde please let me know If I'm missing something. Thanks
linked to: https://github.com/lblod/frontend-reglementaire-bijlage/pull/74
=> enable citation plugin on reglementaire-bijlage

app/components/rdfa-editor-container.hbs, app/components/rdfa-editor-container.js, package-lock.json, package.json
In draft until https://github.com/lblod/ember-rdfa-editor/pull/770 is merged and released
=> Add chrome and firefox hacks plugin and last key pressed plugin

app/controllers/edit.js, app/templates/edit.hbs
Activate new text plugins in reglementaire bijlage per Bart request
=> activate new text plugins

app/components/insert-title-card.js, app/styles/_shame.scss, app/templates/edit.hbs, translations/en-us.yaml, translations/nl-BE.yaml
- change "titel document" to Document-titel everywhere
- fix placeholder text insertion (function was called in the wrong way)
- update the rdfa hover annotation to match
- 
https://binnenland.atlassian.net/browse/GN-4312
=> GN-4312 make document title more distinct from title

app/controllers/edit.js, app/controllers/snippets-management/edit/edit-snippet.js
Fix problems with number variable in QA
none that I know
none
Test in both editors that you can now insert number variables
none
=> Add number node and number view so the number variable is not broken

app/styles/app.scss, app/templates/edit.hbs, app/templates/snippets-management/edit/edit-snippet.hbs
https://binnenland.atlassian.net/browse/GN-4220
```
npm i
ember s --proxy https://dev.reglementairebijlagen.lblod.info
```
See video
https://github.com/lblod/frontend-reglementaire-bijlage/assets/769698/2cac3d97-dba9-41d2-9e5e-36420b32e848
=> GN-4220: Enable generic RDFA insert plugin

app/styles/app.scss, app/templates/regulatory-attachments/edit.hbs
This PR adds the template-comment edit widget to the regulatory statement edit page
=> Add template-comment edit widget

.changeset/sharp-windows-marry.md, .changeset/small-pumpkins-study.md, package-lock.json, package.json
- Update editor to 8.2.0
- Update editor-plugins to 15.2.2
=> Update editor packages

.changeset/wet-bulldogs-fix.md, app/controllers/regulatory-attachments/edit.js, package-lock.json, package.json
The document needs to be a legitimate resource node for the rdfa-tools to work on the root node.
This PR sets up newly created documents this way, using a placeholder URI as detailed in
[GN-4798](https://binnenland.atlassian.net/browse/GN-4798).
Needed for [GN-4773](https://binnenland.atlassian.net/browse/GN-4773)
make RB, see if you can edit the document properties/relationships
=> Set up controller to allow for doc properties

.changeset/slimy-donkeys-travel.md, package-lock.json, package.json
This PR includes an update of `@lblod/ember-rdfa-editor-lblod-plugins` to 17.1.1
=> Update `@lblod/ember-rdfa-editor-lblod-plugins` to 17.1.1

.changeset/gold-vans-drive.md, app/controllers/template-management/edit.js, app/styles/app.scss, app/templates/template-management/edit.hbs
Sets up the mandatee table plugin so we can insert the table placeholder in decision templates.
Currently not yet active in snippets because it still needs a decision node, so that's blocked by the rdfa-aware snippets.
[GN-4899](https://binnenland.atlassian.net/browse/GN-4899)
just run
*KNOWN ISSUES*: doesn't render anything in the publish preview, will make a ticket for that
=> Add mandatee table plugin

.changeset/great-avocados-notice.md, app/templates/snippet-management/edit/edit-snippet.hbs, app/templates/template-management/edit.hbs
I noticed we never added the alignment menu to the toolbar here
[GN-4854](https://binnenland.atlassian.net/browse/GN-4854)
just run
=> Add missing horizontal alignment menu to toolbar

.changeset/ten-shoes-do.md, app/controllers/snippet-management/edit/edit-snippet.js, app/controllers/template-management/edit.js, app/styles/app.scss, app/templates/snippet-management/edit/edit-snippet.hbs, app/templates/template-management/edit.hbs, package-lock.json, package.json
Configures the location plugin and adds the necessary dependencies
[GN-4841](https://binnenland.atlassian.net/browse/GN-4841)
just run and try it
=> Add location plugin

Dockerfile, package-lock.json, package.json, patches/ember-source+4.12.3.patch
This PR includes two changes:
- addition of `patch-package`
- An `ember-source` patch to silence slicing warnings
=> patches: add patch-package patch to silence slicing warning

.changeset/twenty-toes-sort.md, .woodpecker/.build-pr.yml, .woodpecker/.changeset.yml, .woodpecker/.futurenow.yml, .woodpecker/.latest.yml, .woodpecker/.release.yml, .woodpecker/.verify-pr.yml
- Use updated woodpecker syntax
- Move to `woodpeckerci/plugin-docker-buildx` plugin for docker builds
TODO
=> Modernize woodpecker setup

.changeset/long-eagles-rescue.md, .changeset/popular-seas-cheat.md, app/templates/legal/accessibilitystatement.hbs, app/templates/legal/cookiestatement.hbs
This PR includes the following fixes to the legal pages of this app:
- (cookie statement): ensure the links are rendered as `a` tags + update them
- (cookie statement): replace IE link by Microsoft Edge link
- (accessibility statement): fix telephone number link
[GN-4536](https://binnenland.atlassian.net/browse/GN-4536?atlOrigin=eyJpIjoiZGE0OTk4MWEwZTY1NGRjMDhjM2U1ZDBjYWY4NzM4OGUiLCJwIjoiaiJ9)
- Start the app
- Visit the cookie statement page: ensure the links are rendered as `a` tags and resolve correctly
- Visit the accessibility statement: the telephone number link should now be correct
=> GN-4536: fix issues with legal pages
